      PROGRAM MAIN
      CHARACTER(50) GEO3X3_ENCODE
      PRINT*, GEO3X3_ENCODE(35.65858,139.745433,14)
      END PROGRAM MAIN

C     ENCODE FUNCTION
      CHARACTER(50) FUNCTION GEO3X3_ENCODE(LAT,LNG,LEVEL)
      IMPLICIT NONE
      REAL LAT, LNG, FLAT, FLNG, UNIT
      INTEGER LEVEL, I, X, Y
      FLAT = LAT
      FLNG = LNG
      IF (LNG .GE. 0.0) THEN
        GEO3X3_ENCODE = 'E'
      ELSE
        GEO3X3_ENCODE = 'W'
        FLNG = FLNG+180.0
      END IF
C     180:THE NORTH POLE,  0:THE SOUTH POLE
      FLAT = FLAT+90.0
      UNIT = 180.0
      DO 100 I = 1,LEVEL - 1
        UNIT = UNIT / 3
        X = FLOOR(FLNG / UNIT)
        Y = FLOOR(FLAT / UNIT)
        GEO3X3_ENCODE(I + 1:I + 1) = CHAR(X + Y * 3 + 1 + 48)
        FLNG = FLNG - X * UNIT
        FLAT = FLAT - Y * UNIT
100   CONTINUE
      END FUNCTION